version: '2'

services:

  wekandb-dev:
    image: mongo:3.2.19
    container_name: wekan-db-dev
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db-dev:/data/db
      - wekan-db-dump-dev:/dump

  wekan-dev:
    image: wekan:dev
    container_name: wekan-app-dev
    restart: always
    networks:
      - wekan-tier
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:3000
    environment:
      - MONGO_URL=mongodb://wekandb-dev:27017/wekan
      - ROOT_URL=http://localhost:8081
    depends_on:
      - wekandb-dev
    volumes:
      - ./src:/home/wekan/app

volumes:
  wekan-db-dev:
    driver: local
  wekan-db-dump-dev:
    driver: local

networks:
  wekan-tier:
    driver: bridge
