version: '2'

services:

  wekandb:
    image: mongo:3.2.12
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: wekan:dev
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=v0.10.48
        - METEOR_RELEASE=1.3.5.1
        - NPM_VERSION=3.10.10
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost
    depends_on:
      - wekandb
    volumes:
      - ./src:/home/wekan/app

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
