version: '2'

services:

  wekandb-dev:
    image: mongo:3.2.20
    container_name: wekan-db-dev
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db-dev:/data/db
      - wekan-db-dump-dev:/dump

  wekan-dev:
    image: wekan:dev
    container_name: wekan-app-dev
    restart: always
    networks:
      - wekan-tier
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEKAN_UID=${WEKAN_UID}
        - WEKAN_GID=${WEKAN_GID}
    ports:
      - 8081:3000
    environment:
      - MONGO_URL=mongodb://wekandb-dev:27017/wekan
      - ROOT_URL=http://localhost:8081
      - WITH_API=true
      - BROWSER_POLICY_ENABLED=true
      - TRUSTED_URL=''
    depends_on:
      - wekandb-dev
    volumes:
      - ./src/client:/home/wekan/app/client
      - ./src/models:/home/wekan/app/models
      - ./src/config:/home/wekan/app/config
      - ./src/i18n:/home/wekan/app/i18n
      - ./src/server:/home/wekan/app/server

volumes:
  wekan-db-dev:
    driver: local
  wekan-db-dump-dev:
    driver: local

networks:
  wekan-tier:
    driver: bridge
